// Auto-generado por IRE Dashboard
// Fecha: 2026-08-01T07:38:28.998451

const propiedades = [
    {
        id: 'pereyra-6',
        tipo: 'renta',
        categoria: 'Propiedad',
        titulo: 'PEREYRA 6',
        ubicacion: 'Calle Pereyra #XXX, Tehuacán, Puebla',
        precio: 0,
        precioTexto: '$0',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'clavel',
        tipo: 'renta',
        categoria: 'Propiedad',
        titulo: 'CLAVEL',
        ubicacion: 'Calle Clavel, Tehuacán, Puebla',
        precio: 0,
        precioTexto: '$0',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'pereyra-10',
        tipo: 'renta',
        categoria: 'Propiedad',
        titulo: 'PEREYRA 10',
        ubicacion: 'Calle Pereyra #XXX, Tehuacán, Puebla',
        precio: 990.0,
        precioTexto: '$990',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'pereyra-5',
        tipo: 'renta',
        categoria: 'Propiedad',
        titulo: 'PEREYRA 5',
        ubicacion: 'Calle Pereyra #XXX, Tehuacán, Puebla',
        precio: 1780.0,
        precioTexto: '$1,780',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'cuarto-3-16-norte',
        tipo: 'renta',
        categoria: 'Cuarto',
        titulo: 'Cuarto 3 - Edificio 16 Norte',
        ubicacion: 'Calle 16 Norte #127, Col. Serdan, Tehuacán',
        precio: 1900.0,
        precioTexto: '$1,900',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'pereyra-8',
        tipo: 'renta',
        categoria: 'Propiedad',
        titulo: 'PEREYRA 8',
        ubicacion: 'Calle Pereyra #XXX, Tehuacán, Puebla',
        precio: 1900.0,
        precioTexto: '$1,900',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'pereyra-9',
        tipo: 'renta',
        categoria: 'Propiedad',
        titulo: 'PEREYRA 9',
        ubicacion: 'Calle Pereyra #XXX, Tehuacán, Puebla',
        precio: 1900.0,
        precioTexto: '$1,900',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'pereyra-4',
        tipo: 'renta',
        categoria: 'Propiedad',
        titulo: 'PEREYRA 4',
        ubicacion: 'Calle Pereyra #XXX, Tehuacán, Puebla',
        precio: 1996.0,
        precioTexto: '$1,996',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'cuarto-7-16-norte',
        tipo: 'renta',
        categoria: 'Cuarto',
        titulo: 'Cuarto 7 - Edificio 16 Norte',
        ubicacion: 'Calle 16 Norte #127, Col. Serdan, Tehuacán',
        precio: 2090.0,
        precioTexto: '$2,090',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'cuarto-4-16-norte',
        tipo: 'renta',
        categoria: 'Cuarto',
        titulo: 'Cuarto 4 - Edificio 16 Norte',
        ubicacion: 'Calle 16 Norte #127, Col. Serdan, Tehuacán',
        precio: 2500.0,
        precioTexto: '$2,500',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'cuarto-5-16-norte',
        tipo: 'renta',
        categoria: 'Cuarto',
        titulo: 'Cuarto 5 - Edificio 16 Norte',
        ubicacion: 'Calle 16 Norte #127, Col. Serdan, Tehuacán',
        precio: 2500.0,
        precioTexto: '$2,500',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'cuarto-8-16-norte',
        tipo: 'renta',
        categoria: 'Cuarto',
        titulo: 'Cuarto 8 - Edificio 16 Norte',
        ubicacion: 'Calle 16 Norte #127, Col. Serdan, Tehuacán',
        precio: 2500.0,
        precioTexto: '$2,500',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'cuarto-aquiles-serdan',
        tipo: 'renta',
        categoria: 'Cuarto',
        titulo: 'Cuarto Aquiles Serdán',
        ubicacion: 'Calle 16 Norte, Aquiles Serdán, Tehuacán, Puebla',
        precio: 2500.0,
        precioTexto: '$2,500',
        metros: '30 m²' if metros else 'N/A',
        habitaciones: '1',
        banos: '1',
        imagen: 'https://bjzwbpkkazhczwtsxtey.supabase.co/storage/v1/object/public/fotos-propiedades/propiedades-renta/16norte-cuartos/1.webp'
    },
    {
        id: 'pereyra-2',
        tipo: 'renta',
        categoria: 'Propiedad',
        titulo: 'PEREYRA 2',
        ubicacion: 'Calle Pereyra #XXX, Tehuacán, Puebla',
        precio: 2800.0,
        precioTexto: '$2,800',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'cuarto-2-16-norte',
        tipo: 'renta',
        categoria: 'Cuarto',
        titulo: 'Cuarto 2 - Edificio 16 Norte',
        ubicacion: 'Calle 16 Norte #127, Col. Serdan, Tehuacán',
        precio: 3000.0,
        precioTexto: '$3,000',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'pereyra-1',
        tipo: 'renta',
        categoria: 'Propiedad',
        titulo: 'PEREYRA 1',
        ubicacion: 'Calle Pereyra #XXX, Tehuacán, Puebla',
        precio: 3000.0,
        precioTexto: '$3,000',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'pereyra-3',
        tipo: 'renta',
        categoria: 'Propiedad',
        titulo: 'PEREYRA 3',
        ubicacion: 'Calle Pereyra #XXX, Tehuacán, Puebla',
        precio: 3000.0,
        precioTexto: '$3,000',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'cuarto-6-16-norte',
        tipo: 'renta',
        categoria: 'Cuarto',
        titulo: 'Cuarto 6 - Edificio 16 Norte',
        ubicacion: 'Calle 16 Norte #127, Col. Serdan, Tehuacán',
        precio: 3500.0,
        precioTexto: '$3,500',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'cultural',
        tipo: 'renta',
        categoria: 'Propiedad',
        titulo: 'CULTURAL',
        ubicacion: 'Col. Cultural, Tehuacán, Puebla',
        precio: 3500.0,
        precioTexto: '$3,500',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'cuarto-local-16-norte',
        tipo: 'renta',
        categoria: 'Cuarto',
        titulo: 'Cuarto/Local - Edificio 16 Norte',
        ubicacion: 'Calle 16 Norte #127, Col. Serdan, Tehuacán',
        precio: 3700.0,
        precioTexto: '$3,700',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'manantiales',
        tipo: 'renta',
        categoria: 'Propiedad',
        titulo: 'MANANTIALES',
        ubicacion: 'Col. Manantiales, Tehuacán, Puebla',
        precio: 3850.0,
        precioTexto: '$3,850',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'valsequillo',
        tipo: 'renta',
        categoria: 'Propiedad',
        titulo: 'VALSEQUILLO',
        ubicacion: 'Blvd. Valsequillo, Tehuacán, Puebla',
        precio: 4000.0,
        precioTexto: '$4,000',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'local-grande-16-norte',
        tipo: 'renta',
        categoria: 'Local',
        titulo: 'Local Grande - Edificio 16 Norte',
        ubicacion: 'Calle 16 Norte #127, Col. Serdan, Tehuacán',
        precio: 5000.0,
        precioTexto: '$5,000',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'departamento-valsequillo',
        tipo: 'renta',
        categoria: 'Departamento',
        titulo: 'Departamento Valsequillo',
        ubicacion: 'Blvd. Valsequillo, Tehuacán',
        precio: 5000.0,
        precioTexto: '$5,000',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '1',
        imagen: ''
    },
    {
        id: 'jazmin',
        tipo: 'renta',
        categoria: 'Propiedad',
        titulo: 'Casa Jazmín',
        ubicacion: 'Calle Jazmín #432, Col. Jacarandas, Tehuacán, Puebla',
        precio: 5000.0,
        precioTexto: '$5,000',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'oficina-2-norte',
        tipo: 'renta',
        categoria: 'Oficina',
        titulo: 'Oficina/Consultorio Col. Zaragoza',
        ubicacion: 'Privada de 2 norte #233, Col. Zaragoza, Tehuacán, Puebla',
        precio: 5000.0,
        precioTexto: '$5,000',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: 'https://bjzwbpkkazhczwtsxtey.supabase.co/storage/v1/object/public/fotos-propiedades/propiedades-renta/consultorios-2-norte/1.webp'
    },
    {
        id: 'prueba-jardin-123',
        tipo: 'renta',
        categoria: 'Casa',
        titulo: 'Prueba Jardín 123',
        ubicacion: 'Calle de prueba 123',
        precio: 5000.0,
        precioTexto: '$5,000',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '3',
        banos: '2',
        imagen: 'https://bjzwbpkkazhczwtsxtey.supabase.co/storage/v1/object/public/fotos-propiedades/prueba-jardin/1.webp'
    },
    {
        id: 'c-escolar',
        tipo: 'renta',
        categoria: 'Propiedad',
        titulo: 'C. ESCOLAR',
        ubicacion: 'Calle Escolar, Tehuacán, Puebla',
        precio: 5500.0,
        precioTexto: '$5,500',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'prepa-federal',
        tipo: 'renta',
        categoria: 'Propiedad',
        titulo: 'PREPA FEDERAL',
        ubicacion: 'Preparatoria Federal, Tehuacán, Puebla',
        precio: 6600.0,
        precioTexto: '$6,600',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'departamento-4-poniente',
        tipo: 'renta',
        categoria: 'Departamento',
        titulo: 'Departamento 4 Poniente',
        ubicacion: '4 Poniente, Centro, Tehuacán, Puebla',
        precio: 7000.0,
        precioTexto: '$7,000',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '3',
        banos: '1',
        imagen: 'https://bjzwbpkkazhczwtsxtey.supabase.co/storage/v1/object/public/fotos-propiedades/propiedades-renta/departamento_centro/1.webp'
    },
    {
        id: 'suite-ejecutiva-hotel-boutique',
        tipo: 'renta',
        categoria: 'Departamento',
        titulo: 'Suite Ejecutiva Hotel Boutique',
        ubicacion: '1 Poniente, Hotel Boutique Tehuacán, Centro, Tehuacán, Puebla',
        precio: 7500.0,
        precioTexto: '$7,500',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '1',
        banos: '1',
        imagen: 'https://bjzwbpkkazhczwtsxtey.supabase.co/storage/v1/object/public/fotos-propiedades/propiedades-renta/suite_HB/1.webp'
    },
    {
        id: 'camelia-2',
        tipo: 'renta',
        categoria: 'Propiedad',
        titulo: 'CAMELIA 2',
        ubicacion: 'Calle Camelia #XXX, Tehuacán, Puebla',
        precio: 8500.0,
        precioTexto: '$8,500',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'departamento-privada-1-poniente',
        tipo: 'renta',
        categoria: 'Departamento',
        titulo: 'Departamento Privada 1 Poniente',
        ubicacion: 'Privada de la 1 Poniente, Tehuacán, Puebla',
        precio: 8500.0,
        precioTexto: '$8,500',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '3',
        banos: '2',
        imagen: 'https://bjzwbpkkazhczwtsxtey.supabase.co/storage/v1/object/public/fotos-propiedades/propiedades-renta/departamento-priv-1poniente/1.webp'
    },
    {
        id: 'camelia-3',
        tipo: 'renta',
        categoria: 'Propiedad',
        titulo: 'CAMELIA 3',
        ubicacion: 'Calle Camelia #XXX, Tehuacán, Puebla',
        precio: 9500.0,
        precioTexto: '$9,500',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'loft-comercial-escamilla',
        tipo: 'renta',
        categoria: 'Local',
        titulo: 'Loft Comercial Escamilla',
        ubicacion: 'Edificio Escamilla, Tres Oriente esquina con Segunda de Morelos, Centro, Tehuacán, Puebla',
        precio: 10000.0,
        precioTexto: '$10,000',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '1',
        imagen: 'https://bjzwbpkkazhczwtsxtey.supabase.co/storage/v1/object/public/fotos-propiedades/propiedades-renta/loft_centro/1.webp'
    },
    {
        id: 'bodega-16-norte',
        tipo: 'renta',
        categoria: 'Bodega',
        titulo: 'Bodega - Edificio 16 Norte',
        ubicacion: 'Calle 16 Norte #127, Col. Serdan, Tehuacán',
        precio: 12000.0,
        precioTexto: '$12,000',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'casa-francisco-sarabia',
        tipo: 'renta',
        categoria: 'Casa',
        titulo: 'Casa Francisco Sarabia (Casa del Lic)',
        ubicacion: 'Tehuacán, Puebla',
        precio: 16000.0,
        precioTexto: '$16,000',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '2',
        imagen: ''
    },
    {
        id: 'bodega-san-lorenzo',
        tipo: 'renta',
        categoria: 'Bodega',
        titulo: 'Bodega San Lorenzo',
        ubicacion: 'San Lorenzo, Tehuacán, Puebla',
        precio: 23000.0,
        precioTexto: '$23,000',
        metros: '400 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: 'https://bjzwbpkkazhczwtsxtey.supabase.co/storage/v1/object/public/fotos-propiedades/propiedades-renta/bodega-san-lorenzo400/1.webp'
    },
    {
        id: 'bodega-av-cuauhtemoc',
        tipo: 'renta',
        categoria: 'Bodega',
        titulo: 'Bodega Av. Cuauhtémoc',
        ubicacion: 'Av. Cuauhtémoc, Tehuacán, Puebla',
        precio: 35000.0,
        precioTexto: '$35,000',
        metros: '720 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: 'https://bjzwbpkkazhczwtsxtey.supabase.co/storage/v1/object/public/fotos-propiedades/propiedades-renta/bodega-av-cuauctemoc/1.webp'
    },
    {
        id: '5-norte',
        tipo: 'renta',
        categoria: 'Propiedad',
        titulo: '5 NORTE',
        ubicacion: '5 Norte #XXX, Tehuacán, Puebla',
        precio: 38000.0,
        precioTexto: '$38,000',
        metros: '0 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: ''
    },
    {
        id: 'bodega-san-diego',
        tipo: 'renta',
        categoria: 'Bodega',
        titulo: 'Bodega San Diego',
        ubicacion: 'San Diego, Tehuacán, Puebla',
        precio: 60000.0,
        precioTexto: '$60,000',
        metros: '900 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: 'https://bjzwbpkkazhczwtsxtey.supabase.co/storage/v1/object/public/fotos-propiedades/propiedades-renta/bodega-san-diego/1.webp'
    },
    {
        id: 'bodega-santa-cruz-buenavista',
        tipo: 'renta',
        categoria: 'Bodega',
        titulo: 'Bodega Comercial Santa Cruz Buenavista',
        ubicacion: 'Calzada Zavaleta, Santa Cruz Buenavista, Puebla',
        precio: 670000.0,
        precioTexto: '$670,000',
        metros: '2750 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '5',
        imagen: 'https://bjzwbpkkazhczwtsxtey.supabase.co/storage/v1/object/public/fotos-propiedades/propiedades-renta/bodega-santa-cruz-buenavista/1.webp'
    },
    {
        id: 'terreno-parque-industrial2',
        tipo: 'venta',
        categoria: 'Terreno',
        titulo: 'Terreno Parque Industrial II',
        ubicacion: 'Santiago Miahuatlán, Tehuacán',
        precio: 300000.0,
        precioTexto: '$300,000',
        metros: '120 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: 'https://bjzwbpkkazhczwtsxtey.supabase.co/storage/v1/object/public/fotos-propiedades/propiedades-venta/terreno-parque-industrial2/1.webp'
    },
    {
        id: 'terreno-antigua-magdalena',
        tipo: 'venta',
        categoria: 'Terreno',
        titulo: 'Terreno Antigua Magdalena',
        ubicacion: 'Antigua Magdalena, San Lorenzo Teotipilco, Tehuacan, Puebla',
        precio: 2950000.0,
        precioTexto: '$2,950,000',
        metros: '522 m²' if metros else 'N/A',
        habitaciones: '0',
        banos: '0',
        imagen: 'https://bjzwbpkkazhczwtsxtey.supabase.co/storage/v1/object/public/fotos-propiedades/propiedades-venta/terreno-san-lorenzo/1.webp'
    },
    {
        id: 'casa-cinco-bosques',
        tipo: 'venta',
        categoria: 'Casa',
        titulo: 'Casa Cinco Bosques',
        ubicacion: 'Fracc. Cinco Bosques, Tehuacán',
        precio: 8000000.0,
        precioTexto: '$8,000,000',
        metros: '400 m²' if metros else 'N/A',
        habitaciones: '4',
        banos: '3',
        imagen: 'https://bjzwbpkkazhczwtsxtey.supabase.co/storage/v1/object/public/fotos-propiedades/propiedades-venta/casa-cinco-bosques/1.webp'
    },
    {
        id: 'casa-francisco-sarabia-venta',
        tipo: 'venta',
        categoria: 'Casa',
        titulo: 'Casa Francisco Sarabia',
        ubicacion: 'Tehuacán, Puebla',
        precio: 14000000.0,
        precioTexto: '$14,000,000',
        metros: '404 m²' if metros else 'N/A',
        habitaciones: '4',
        banos: '3',
        imagen: 'https://bjzwbpkkazhczwtsxtey.supabase.co/storage/v1/object/public/fotos-propiedades/propiedades-venta/casa-francisco-sarabia/1.webp'
    },
];

// Exportar para uso global
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { propiedades };
}